version: '3.8'

services:
  backend:
    build: ./
#    image: doridoro/oc_lettings_site:1.1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=oc_lettings_site.settings-local
