name: Continuous Integration and Delivery

on:
  push:
    branches:
      - 'dev/*'
  pull_request:
    branches:
      - 'dev/*'

jobs:
  test_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check migrations
        run: python manage.py check

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Run app tests
        run: python manage.py test

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Remove docker container
        run: docker rm oc_lettings-backend-1

      - name: Build the docker-compose image
        run: docker compose up --build

      - name: Check running docker container
        run: docker ps

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#  docker_actions:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: doridoro/oc_lettings_site:latest
