name: Continuous Integration and Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#    paths-ignore:
#      - 'coverage/**'
#      - 'devdist/**'
#      - 'dist/**'
#      - 'docs/**'

# check the coverage
#  linting et la suite de tests et vérifie que la couverture de test est supérieure à 80 % ;
jobs:
  test_app:
    name: Testing the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        id: flake8
        continue-on-error: true
        run: flake8

      - name: Run app tests
        env:
          SECRET_KEY: ${{ security.SECRET_KEY }}
        run: python manage.py test

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker-compose image
        run: docker compose up --build

      - name: Check running docker container
        run: docker ps

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#  docker_actions:
#    name: Docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: doridoro/oc_lettings_site:latest
