name: Continuous Integration and Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_app:
    name: Testing the app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8

      - name: Run app tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DEBUG: ${{ secrets.DEBUG }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          coverage run --source='.' --omit='*/migrations/*' manage.py test
          coverage report

#  docker:
#    name: Docker
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Build the Docker image
#        env:
#          SECRET_KEY: ${{ secrets.SECRET_KEY }}
#          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
#          DEBUG: ${{ secrets.DEBUG }}
#          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
#        run: |
#          docker build -t oc_lettings .
#          docker images
#
#      - name: Tag the Docker image
#        run: docker tag oc_lettings:latest doridoro/oc_lettings_site:latest
#
#      - name: Run Docker container
#        run: docker run -dp 8000:8000 oc_lettings
#
#      - name: Check running docker container
#        run: docker ps
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Push Docker image to Docker Hub
#        run: docker push doridoro/oc_lettings_site:latest

  docker_actions:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: doridoro/oc_lettings_site:latest
